### CONTENEDORES

# Registrar contenedor con sensores
POST http://192.168.1.134:9000/api/contenedor
Content-Type: application/json

{
  "nombreZona": "Universidad Tecnologica de la Sierra Hidalguense",
  "tipoContenedor": "Inorganico",
  "ubicacion": {
    "lat": 20.89215,
    "lng": -98.58374
  },
  "configSensor": {
    "distanciaMin": 5,
    "distanciaMax": 50,
    "temperaturaMax": 40
  }
}

### Obtener todos los contenedores
GET https://api-rest-bin-tracker.onrender.com/api/contenedor/BT002

### Editar contenedor por matrícula
PUT http://192.168.1.134:9000/api/contenedor/BT088
Content-Type: application/json

{
  "nombreZona": "Universidad Tecnologica de la Sierra Hidalguense",
  "tipoContenedor": "Peligroso"
}

### Eliminar contenedor
DELETE http://192.168.1.134:9000/api/contenedor/BT086

### Obtener contenedores asignados a un usuario
GET https://api-rest-bin-tracker.onrender.com/api/usuarios

### Asignar contenedor a usuario
PUT http://192.168.1.134:9000/api/contenedor/ID_CONTENEDOR/asignar
Content-Type: application/json

{
  "asignadoA": "ID_USUARIO"
}


### USUARIOS

# Crear usuario (normal) con asignación de contenedores
POST https://api-rest-bin-tracker.onrender.com/api/usuarios
Content-Type: application/json

{
  "nombreCompleto": "Agustindslfge Zavaleta",
  "usuario": "Robesdfsdft",
  "correo": "betoazdoefjhueyaSFpGGVa@gmail.com",
  "telefono": "7712382596",
  "password": "12345678",
  "creadoPor": "ID_DEL_ADMIN",
  "contenedoresAsignados": ["BT001", "BT002"]
}

### Obtener todos los usuarios (superadmin)
GET https://api-rest-bin-tracker.onrender.com/api/contenedor/usuarios

### Obtener usuarios creados por admin
GET http://192.168.1.134:9000/api/usuarios/creadosPor/ID_DEL_ADMIN

### Editar usuario por matrícula
PUT http://192.168.1.134:9000/api/usuarios/002
Content-Type: application/json

{
  "nombreCompleto": "Roberto Agustin Zavaleta",
  "usuario": "Robert08",
  "correo": "betoazhueyapa@gmail.com",
  "telefono": "7712382596"
}

### Eliminar usuario
DELETE http://192.168.1.134:9000/api/usuarios/002


### SENSORES

# Enviar datos de sensor
POST http://192.168.1.135:9000/api/sensor
Content-Type: application/json

{
  "matriculaContenedor": "BT001",
  "temperatura": 22.8,
  "distancia": 3
}

### Obtener registros del sensor de un contenedor
GET https://api-rest-bin-tracker.onrender.com/api/sensor/BT001/ultimo


###
POST https://api-rest-bin-tracker.onrender.com/api/sensor
Content-Type: application/json

{
  "matriculaContenedor": "BT001",
  "temperatura": 22.8,
  "distancia": 50
}

### Obtener último registro
GET http://192.168.1.135:9000/api/sensor/BT003/ultimo

### Obtener estadísticas
GET https://api-rest-bin-tracker.onrender.com/api/contenedor/


### CONTACTOS

# Registrar contacto
POST http://192.168.1.134:9000/api/contacto
Content-Type: application/json

{
  "nombre": "Agustin Zavaleta",
  "correo": "betoazhJueyapa@gmail.com",
  "telefono": "7712382596",
  "mensaje": "Hola, soy un mensaje de prueba"
}

### Ver todos los contactos
GET http://192.168.1.134:9000/api/contacto

###
POST http://192.168.1.134:9000/api/login
Content-Type: application/json

{
  "usuario": "superadmin",
  "password": "admin123"
}


###
GET https://api-rest-bin-tracker.onrender.com/api/login